In [1]:
import numpy as np

In [2]:
arr= np.random.randint(1,100,10)# 1 ile 100 arasında 10 karakterli rastgele dizi oluşturma
arr

array([60, 60, 72, 97, 60, 39, 13, 67,  4, 38])

In [3]:
arr.sort() # diziyi küçükten büyüğe doğru sıralar
arr

array([ 4, 13, 38, 39, 60, 60, 60, 67, 72, 97])

In [4]:
arr2 = arr.copy() # arr dizisini arr2 ye kopyalıyor
arr2[4] = 24 # arr2 dizisinin ilk elemanını 24 yapıyorum
arr2

array([ 4, 13, 38, 39, 24, 60, 60, 67, 72, 97])

In [5]:
arr # arr dizisinde herhangi bir değişiklik yok

array([ 4, 13, 38, 39, 60, 60, 60, 67, 72, 97])

In [6]:
print(arr2.base) # dizi copyalanmışmı yoksa görüntüsümü alınmış tespit etmek için base fonksiyonu kullanılır 
# eğer değer none ise kopyalanmış değilse görüntüsü alınmıştır

None


In [7]:
arr2 = arr.view() # arr dizisini arr2 ye kopyalıyor
arr2[4] = 25 # arr2 dizisinin ilk elemanını 25 yapıyorum
arr2

array([ 4, 13, 38, 39, 25, 60, 60, 67, 72, 97])

In [8]:
arr # arr dizisinde arr2 de yaptığım değişiklikler arr üzerinde uygulanmış oluyor

array([ 4, 13, 38, 39, 25, 60, 60, 67, 72, 97])

In [9]:
print(arr2.base) # dizi copyalanmışmı yoksa görüntüsümü alınmış tespit etmek için base fonksiyonu kullanılır 
# eğer değer none ise kopyalanmış değilse görüntüsü alınmıştır

[ 4 13 38 39 25 60 60 67 72 97]


In [10]:
# 3 boyutlu elemanları rastgele olan 2ye 6lık bir dizi 2 satır 6 sütun
newarr=np.array([[np.random.randint(1,50,6)],[np.random.randint(1,50,6)]])
newarr

array([[[47, 19, 35, 17, 45, 15]],

       [[17, 44, 15, 40, 38, 20]]])

In [11]:
newarr.sort() # diziyi küçükten büyüğe doğru sıralar
newarr

array([[[15, 17, 19, 35, 45, 47]],

       [[15, 17, 20, 38, 40, 44]]])

In [12]:
newarr.sum(axis=0) # çok boyutlu dizilerde satır ve sütun olayı vardır buradaki sütunların toplamını verir

array([[30, 34, 39, 73, 85, 91]])

In [13]:
newarr = newarr.reshape(4,3)
print(newarr,"\n")

print(newarr.sum(axis=0),"\n") # sütunların toplamı

print(newarr.sum(axis=1),"\n") # satırların toplamı

[[15 17 19]
 [35 45 47]
 [15 17 20]
 [38 40 44]] 

[103 119 130] 

[ 51 127  52 122] 



In [14]:
newarr.sum(axis=0) # sütunların toplamı

array([103, 119, 130])

In [15]:
newarr.sum(axis=1) # satırların toplamı

array([ 51, 127,  52, 122])